### ISSUE TITLE
Could not locate the bindings file. Tried

### ISSUE THREAD

**Issue by zzzgit** [clayrisser/open-terminal#5]
```
[Running] ts-node "/Users/luochao/Desktop/projects/vita-nova/src/sessionid/kskks copy.ts"
/Users/luochao/Desktop/projects/vita-nova/node_modules/bindings/bindings.js:126
  err = new Error(
        ^
Error: Could not locate the bindings file. Tried:
 → /Users/luochao/Desktop/projects/vita-nova/node_modules/node-sigar/build/sigar.node
 → /Users/luochao/Desktop/projects/vita-nova/node_modules/node-sigar/build/Debug/sigar.node
 → /Users/luochao/Desktop/projects/vita-nova/node_modules/node-sigar/build/Release/sigar.node
 → /Users/luochao/Desktop/projects/vita-nova/node_modules/node-sigar/out/Debug/sigar.node
 → /Users/luochao/Desktop/projects/vita-nova/node_modules/node-sigar/Debug/sigar.node
 → /Users/luochao/Desktop/projects/vita-nova/node_modules/node-sigar/out/Release/sigar.node
 → /Users/luochao/Desktop/projects/vita-nova/node_modules/node-sigar/Release/sigar.node
 → /Users/luochao/Desktop/projects/vita-nova/node_modules/node-sigar/build/default/sigar.node
 → /Users/luochao/Desktop/projects/vita-nova/node_modules/node-sigar/compiled/16.13.0/darwin/x64/sigar.node
 → /Users/luochao/Desktop/projects/vita-nova/node_modules/node-sigar/addon-build/release/install-root/sigar.node
 → /Users/luochao/Desktop/projects/vita-nova/node_modules/node-sigar/addon-build/debug/install-root/sigar.node
 → /Users/luochao/Desktop/projects/vita-nova/node_modules/node-sigar/addon-build/default/install-root/sigar.node
 → /Users/luochao/Desktop/projects/vita-nova/node_modules/node-sigar/lib/binding/node-v93-darwin-x64/sigar.node
    at bindings (/Users/luochao/Desktop/projects/vita-nova/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/Users/luochao/Desktop/projects/vita-nova/node_modules/node-sigar/src/index.ts:3:15)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .js] (/usr/local/lib/node_modules/ts-node/src/index.ts:1449:43)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /Users/luochao/Desktop/projects/vita-nova/node_modules/open-terminal/lib/index.js:17:1013 {
  tries: [
    '/Users/luochao/Desktop/projects/vita-nova/node_modules/node-sigar/build/sigar.node',
    '/Users/luochao/Desktop/projects/vita-nova/node_modules/node-sigar/build/Debug/sigar.node',
    '/Users/luochao/Desktop/projects/vita-nova/node_modules/node-sigar/build/Release/sigar.node',
    '/Users/luochao/Desktop/projects/vita-nova/node_modules/node-sigar/out/Debug/sigar.node',
    '/Users/luochao/Desktop/projects/vita-nova/node_modules/node-sigar/Debug/sigar.node',
    '/Users/luochao/Desktop/projects/vita-nova/node_modules/node-sigar/out/Release/sigar.node',
    '/Users/luochao/Desktop/projects/vita-nova/node_modules/node-sigar/Release/sigar.node',
    '/Users/luochao/Desktop/projects/vita-nova/node_modules/node-sigar/build/default/sigar.node',
    '/Users/luochao/Desktop/projects/vita-nova/node_modules/node-sigar/compiled/16.13.0/darwin/x64/sigar.node',
    '/Users/luochao/Desktop/projects/vita-nova/node_modules/node-sigar/addon-build/release/install-root/sigar.node',
    '/Users/luochao/Desktop/projects/vita-nova/node_modules/node-sigar/addon-build/debug/install-root/sigar.node',
    '/Users/luochao/Desktop/projects/vita-nova/node_modules/node-sigar/addon-build/default/install-root/sigar.node',
    '/Users/luochao/Desktop/projects/vita-nova/node_modules/node-sigar/lib/binding/node-v93-darwin-x64/sigar.node'
  ]
}

[Done] exited with code=1 in 1.619 seconds


```

**Comment by jeremiahlachica** [comment]
Having the same issue. Anyone able to fix or has workaround?

**Comment by bpetrified** [comment]
Same here, It has been working fine until I delete node_modules and reinstall everything again.
I need to copy node_modules/node-sigar folder from a working machine to avoid this error.
I guess it is something about node-gyp/pre-gyp that it cannot build node-sigar after installation.
